[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino

; Seri port hız ayarı test/çalışma sırasında değiştirilebilir
monitor_speed = 500000

lib_deps =
  Wire
  https://github.com/teemuatlut/TMCStepper.git
  https://github.com/waspinator/AccelStepper.git

build_flags =
  -O2
  -std=gnu++17
  -DARDUINO_USB_MODE=1
